spring.application.name=URBANFOOD

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=URBANFOOD
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Format SQL in logs (optional)
spring.jpa.properties.hibernate.format_sql=true

# MongoDB settings
spring.data.mongodb.uri=mongodb://localhost:27017/urbanfooddb


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
